### ISSUE TITLE
Control Center background blur / color issue 

### ISSUE THREAD

**Issue by johnstilwell20** [NoisyFlake/MagmaEvo-support#22]
**Describe the bug**
When sliding to open the control center, the default blurred background doesn’t change to a customized background until after letting go.

**To Reproduce**
1. Go to Magma Evo settings > Miscellaneous
2. Change “Background Color” to anything that is not the default
3. Swipe down on top right to open the Control Center but don’t let go, the default background blur / color will not update to what it was changed to until after letting go

**Expected behavior**
The background blur and color should be whatever it was set to in the settings as soon as you start to swipe down.

**Screenshots**
![9357B420-8831-4AC9-AB58-E28237F3ABBA](https://user-images.githubusercontent.com/61131156/74622198-e6649e80-510d-11ea-9bb6-260f10aad1bd.jpeg)

![C5B072A1-7048-4916-9B28-8AE94D45C53C](https://user-images.githubusercontent.com/61131156/74622192-e49adb00-510d-11ea-897a-f18328914449.jpeg)

**iOS Version:**
iOS 13.3

**Device:**
iPhone 11 Pro Max

**Tweak list:**
https://pastebin.com/YMnweiqK

**Additional context**
Issue persists whether or not dark mode is enabled

**Comment by NoisyFlake** [comment]
I can make it so that the background color appears as soon as you start swiping down, but that would only move the problem to another point. People then would complain that the full background color is already active before they can see their modules etc. 

Implementing a smooth transition here is not that easy due to the way Apple implemented their own CC blur effect here. I'll keep it in mind and will try to fix it sometimes in the future.
